# docker-compose.yml
version: '3.8'

services:
  db:
    # Imagem oficial do PostgreSQL
    image: postgres:16-alpine
    container_name: postgres-atividade3-fiap
    restart: always
    
    # Variáveis de ambiente para configuração do banco de dados
    environment:
      POSTGRES_DB: atividade3-fiap
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    
    # Mapeamento da porta
    ports:
      - "5432:5432"
      
    # Mapeamento de volumes
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./init_files/init.sql:/docker-entrypoint-initdb.d/init.sql
      

volumes:
  postgres_data: